<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<Platforms>AnyCPU;x64</Platforms>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
		<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="accoremgd">
			<HintPath>..\..\..\..\..\Program Files\Autodesk\AutoCAD 2025\accoremgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="acdbmgd">
			<HintPath>..\..\..\..\..\Program Files\Autodesk\AutoCAD 2025\acdbmgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="acmgd">
			<HintPath>..\..\..\..\..\Program Files\Autodesk\AutoCAD 2025\acmgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="AecBaseMgd">
			<HintPath>..\..\..\..\..\Program Files\Autodesk\AutoCAD 2025\ACA\AecBaseMgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="AeccDbMgd">
			<HintPath>..\..\..\..\..\Program Files\Autodesk\AutoCAD 2025\C3D\AeccDbMgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

</Project>
